substitutions:
  name: "esphome-web-xxxxxx-2-1"
  friendly_name: "ESPHome Web xxxxxx 2.1"
  device_description: "Makerfabs MaTouch ESP32-S3 Rotary IPS Display with Touch 2.1 ST7701"
  project_name: "Makerfabs.MaTouch-ESP32-S3-Rotary-IPS-Display-with-Touch-2_1-ST7701"
  project_version: "1.0.0"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: "${project_name}"
    version: "${project_version}"
  min_version: 2024.11.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
    board_build.arduino.memory_type: qio_opi
    build_flags: "-DBOARD_HAS_PSRAM"
    board_upload.maximum_ram_size: 524288
  on_boot:
    priority: 600
    then:
      - delay: 2s
      - lvgl.widget.hide: boot_screen
esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
psram:
  speed: 80MHz
  mode: octal

# Enable logging
logger:
  level: DEBUG 

debug:
  update_interval: 30s
# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

mdns:
  disabled: false
  
wifi:
  power_save_mode: none
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

captive_portal:

external_components:
  - source: 
      type: local
      path: components
    components: [ cst826 ]
# --------------------------------------
# -            HARDWARE                -
# --------------------------------------

i2c:
  - id: i2c_bus
    sda: 17
    scl: 18
    scan: true
    frequency: 400kHz

spi:
  id: spi_bus
  mosi_pin: GPIO0
  clk_pin: GPIO46

output:
  # - platform: ledc
  #   pin: GPIO3
  #   id: buzzer
  - platform: ledc
    pin: GPIO38
    id: backlight_output

# --------------------------------------
# -            DISPLAY                 -
# --------------------------------------
display:
  - platform: st7701s
    id: round_display
    auto_clear_enabled: false
    color_order: rgb
    data_rate: 10MHz
    spi_mode: MODE3
    dimensions:
      width: 480
      height: 480
    cs_pin: GPIO1
    #reset_pin: GPIO
    de_pin: GPIO2
    hsync_pin: GPIO3
    vsync_pin: GPIO42
    pclk_pin: GPIO45
    pclk_frequency: 12MHz
    pclk_inverted: false
    hsync_front_porch: 10
    hsync_pulse_width: 8
    hsync_back_porch: 50
    vsync_front_porch: 10
    vsync_pulse_width: 8
    vsync_back_porch: 20
    data_pins:
      red:
        - 11        #r1
        - 15        #r2
        - 12        #r3
        - 16        #r4
        - 21        #r5
      green:
        - 39        #g0
        - 07        #g1
        - 47        #g2
        - 08        #g3
        - 48        #g4
        - 09        #g5
      blue:
        - 04        #b1
        - 41        #b2
        - 05        #b3
        - 40        #b4
        - 06        #b5
    init_sequence:
      - [0x01]
      - delay 120ms
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10]
      - [0xC0, 0x3B, 0x00]
      - [0xC1, 0x0B, 0x02]
      - [0xC2, 0x00, 0x02]
      - [0xCC, 0x10]
      - [0xCD, 0x08]
      - [0xB0, 0x02, 0x13, 0x1B, 0x0D, 0x10, 0x05, 0x08, 0x07, 0x07, 0x24, 0x04, 0x11, 0x0E, 0x2C, 0x33, 0x1D]
      - [0xB1, 0x05, 0x13, 0x1B, 0x0D, 0x11, 0x05, 0x08, 0x07, 0x07, 0x24, 0x04, 0x11, 0x0E, 0x2C, 0x33, 0x1D]
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x11]
      - [0xB0, 0x5d]
      - [0xB1, 0x43]
      - [0xB2, 0x81]
      - [0xB3, 0x80]
      - [0xB5, 0x43]
      - [0xB7, 0x85]
      - [0xB8, 0x20]
      - [0xC1, 0x78]
      - [0xC2, 0x78]
      - [0xD0, 0x88]
      - [0xE0, 0x00, 0x00, 0x02]
      - [0xE1, 0x03, 0xA0, 0x00, 0x00, 0x04, 0xA0, 0x00, 0x00, 0x00, 0x20, 0x20]
      - [0xE2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      - [0xE3, 0x00, 0x00, 0x11, 0x00]
      - [0xE4, 0x22, 0x00]
      - [0xE5, 0x05, 0xEC, 0xA0, 0xA0, 0x07, 0xEE, 0xA0, 0xA0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      - [0xE6, 0x00, 0x00, 0x11, 0x00]
      - [0xE7, 0x22, 0x00]
      - [0xE8, 0x06, 0xED, 0xA0, 0xA0, 0x08, 0xEF, 0xA0, 0xA0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      - [0xEB, 0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x00]
      - [0xEd, 0xFF, 0xFF, 0xFF, 0xBA, 0x0A, 0xBF, 0x45, 0xFF, 0xFF, 0x54, 0xFB, 0xA0, 0xAB, 0xFF, 0xFF, 0xFF]
      - [0xEF, 0x10, 0x0D, 0x04, 0x08, 0x3F, 0x1F]
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x13]
      - [0xEF, 0x08]
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x00]
      - [0x36, 0x08]
      - [0x3A, 0x60]
      - [0x11]
      - delay 100ms
      - [0x29]
      - delay 50ms

touchscreen:
  platform: cst826
  id: touch
  #interrupt_pin: GPIO40
  #reset_pin: GPIO16
  i2c_id: i2c_bus
  skip_probe: True
  update_interval: 25ms
  #touch_timeout: 5ms
  on_touch:
    - logger.log:
        format: Touch at (%d, %d)
        args: [touch.x, touch.y]
    - lambda: |-
        ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
            touch.x,
            touch.y,
            touch.x_raw,
            touch.y_raw
            );
  on_release:
    - if:
        condition: lvgl.is_paused
        then:
          - logger.log: "LVGL resuming"
          - lvgl.resume:
          - lvgl.widget.redraw:
    - light.turn_on: 
        id: display_backlight
        brightness: 100%

# --------------------------------------
# -            GUI                     -
# --------------------------------------
font:
  - file: "gfonts://Roboto"
    id: roboto24
    size: 24
    bpp: 4
    glyphsets: GF_Latin_Core
  - file: "gfonts://Roboto"
    id: roboto32
    size: 32
    bpp: 4
    glyphsets: GF_Latin_Core
  - file: "gfonts://Roboto"
    id: roboto48
    size: 48
    bpp: 4
    glyphsets: GF_Latin_Core
  - file: "gfonts://Roboto"
    id: roboto64
    size: 64
    bpp: 4
    glyphsets: GF_Latin_Core
image:
  - file: https://esphome.io/_static/favicon-512x512.png
    id: boot_logo
    resize: 200x200
    type: RGB565
    transparency: opaque

lvgl:
  displays:
    - round_display
  touchscreens:
    - touch
  encoders:
    sensor: encoder
    enter_button: front_button
  on_idle:
    timeout: !lambda "return (id(display_timeout).state * 1000);"
    then:
    - logger.log: "LVGL is idle"
    - light.turn_on: 
        id: display_backlight
        brightness: 20%
    #- lvgl.pause:
  default_font: roboto32
  top_layer:
    widgets:
      # make sure it's the last one in this list:
      - obj:
          id: boot_screen
          x: 0
          y: 0
          width: 100%
          height: 100%
          bg_color: black
          bg_opa: COVER
          radius: 0
          pad_all: 0
          border_width: 0
          widgets:
            - image:
                align: CENTER
                src: boot_logo
                y: -40
            - spinner:
                align: CENTER
                y: 95
                height: 50
                width: 50
                spin_time: 1s
                arc_length: 60deg
                arc_width: 8
                indicator:
                  arc_color: 0x18bcf2
                  arc_width: 8
          on_press:
            - lvgl.widget.hide: boot_screen


# --------------------------------------
# -            SENSORS                 -
# --------------------------------------
binary_sensor:
  - platform: gpio
    name: Button
    id: front_button
    pin: 
      number: GPIO14
      inverted: true

sensor:
  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    type:
      timestamp
    entity_category: "diagnostic"

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

  - platform: rotary_encoder
    id: encoder
    pin_a: GPIO10
    pin_b: GPIO13

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: "diagnostic"
    ssid:
      name: "Connected SSID"
      entity_category: "diagnostic"
    mac_address:
      name: "Mac Address"
      entity_category: "diagnostic"

  #  Creates a sensor showing when the device was last restarted
  - platform: template
    name: 'Last Restart'
    id: device_last_restart
    icon: mdi:clock
    entity_category: "diagnostic"
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - minutes: '*'
        seconds: 0/1
        then:
          - script.execute: time_update
    on_time_sync:
      then:
        - script.execute: time_update
  - platform: sntp
    id: sntp_time
  # Define the timezone of the device
    timezone: ""
  # Change sync interval from default 5min to 6 hours (or as set in substitutions)
    update_interval: 6h
  # Set specific sntp servers to use
    servers:
      - "0.pool.ntp.org"
      - "1.pool.ntp.org"
      - "2.pool.ntp.org"
  # Publish the time the device was last restarted
    on_time_sync:
      then:
        # Update last restart time, but only once.
        - if:
            condition:
              lambda: 'return id(device_last_restart).state == "";'
            then:
              - text_sensor.template.publish:
                  id: device_last_restart
                  state: !lambda 'return id(sntp_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'
script:
  - id: time_update
    then:
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
      # - lvgl.label.update:
      #     id: label_time
      #     text: !lambda |-
      #       auto time = id(sntp_time).now();
      #       return time.strftime("%H:%M:%S");
number:
  - platform: template
    name: Screen timeout
    optimistic: true
    id: display_timeout
    unit_of_measurement: "s"
    initial_value: 45
    restore_value: true
    min_value: 10
    max_value: 180
    step: 5
    mode: slider
light:
  - platform: monochromatic
    name: "Backlight"
    output: backlight_output
    id: display_backlight
    restore_mode: ALWAYS_ON
